	; Strings to accompany .\chest-test.zap

	.GSTR STR?5," are"
	.GSTR STR?24," doesn't"
	.GSTR STR?23," don't"
	.GSTR STR?6," is"
	.GSTR STR?1," Try rephrasing the command."
	.GSTR STR?0,"

Chest Test Game
This is only a test.
"
	.GSTR STR?31,"A small, white room, designed only for testing."
	.GSTR STR?33,"Baseball."
	.GSTR STR?26,"climb"
	.GSTR STR?12,"close"
	.GSTR STR?34,"Cold showers."
	.GSTR STR?3,"get inside"
	.GSTR STR?22,"give things to"
	.GSTR STR?21,"it"
	.GSTR STR?32,"It reads: If you can read this, the test was successful."
	.GSTR STR?27,"Jumping in place"
	.GSTR STR?13,"lock"
	.GSTR STR?4,"look inside"
	.GSTR STR?11,"open"
	.GSTR STR?7,"pick up"
	.GSTR STR?19,"Pulling"
	.GSTR STR?18,"Pushing"
	.GSTR STR?9,"put things in"
	.GSTR STR?8,"put things on"
	.GSTR STR?15,"read"
	.GSTR STR?30,"Recklessly incinerating"
	.GSTR STR?29,"Rubbing"
	.GSTR STR?16,"switch on and off"
	.GSTR STR?17,"Taking your frustration out on"
	.GSTR STR?20,"them"
	.GSTR STR?14,"unlock"
	.GSTR STR?28,"wake"
	.GSTR STR?25,"Waving your hands"
	.GSTR STR?10,"wear"
	.GSTR STR?2,"You can't go that way."
	.ENDI
