	; Strings to accompany audiotest.zap

	.GSTR STR?6," are"
	.GSTR STR?25," doesn't"
	.GSTR STR?24," don't"
	.GSTR STR?7," is"
	.GSTR STR?1," Try rephrasing the command."
	.GSTR STR?35,"Baseball."
	.GSTR STR?27,"climb"
	.GSTR STR?13,"close"
	.GSTR STR?36,"Cold showers."
	.GSTR STR?4,"get inside"
	.GSTR STR?23,"give things to"
	.GSTR STR?22,"it"
	.GSTR STR?28,"Jumping in place"
	.GSTR STR?14,"lock"
	.GSTR STR?5,"look inside"
	.GSTR STR?12,"open"
	.GSTR STR?8,"pick up"
	.GSTR STR?0,"PRESS A BUTTON"
	.GSTR STR?20,"Pulling"
	.GSTR STR?19,"Pushing"
	.GSTR STR?10,"put things in"
	.GSTR STR?9,"put things on"
	.GSTR STR?16,"read"
	.GSTR STR?31,"Recklessly incinerating"
	.GSTR STR?30,"Rubbing"
	.GSTR STR?17,"switch on and off"
	.GSTR STR?18,"Taking your frustration out on"
	.GSTR STR?21,"them"
	.GSTR STR?34,"There are no exits in that direction."
	.GSTR STR?33,"There isn't an exit that way."
	.GSTR STR?15,"unlock"
	.GSTR STR?29,"wake"
	.GSTR STR?26,"Waving your hands"
	.GSTR STR?11,"wear"
	.GSTR STR?32,"You are in a small sound booth."
	.GSTR STR?2,"You can't go that way."
	.GSTR STR?3,"You look like you're up for an adventure."
	.ENDI
