	; Strings to accompany .\attack-test.zap

	.GSTR STR?4," are"
	.GSTR STR?23," doesn't"
	.GSTR STR?22," don't"
	.GSTR STR?5," is"
	.GSTR STR?1," Try rephrasing the command."
	.GSTR STR?0,"ATTACKBIT Tester
An interactive fiction test by KV"
	.GSTR STR?31,"Baseball."
	.GSTR STR?25,"climb"
	.GSTR STR?11,"close"
	.GSTR STR?32,"Cold showers."
	.GSTR STR?30,"get inside"
	.GSTR STR?21,"give things to"
	.GSTR STR?20,"it"
	.GSTR STR?26,"Jumping in place"
	.GSTR STR?12,"lock"
	.GSTR STR?3,"look inside"
	.GSTR STR?10,"open"
	.GSTR STR?6,"pick up"
	.GSTR STR?18,"Pulling"
	.GSTR STR?17,"Pushing"
	.GSTR STR?8,"put things in"
	.GSTR STR?7,"put things on"
	.GSTR STR?14,"read"
	.GSTR STR?29,"Recklessly incinerating"
	.GSTR STR?28,"Rubbing"
	.GSTR STR?15,"switch on and off"
	.GSTR STR?16,"Taking your frustration out on"
	.GSTR STR?19,"them"
	.GSTR STR?13,"unlock"
	.GSTR STR?27,"wake"
	.GSTR STR?24,"Waving your hands"
	.GSTR STR?9,"wear"
	.GSTR STR?2,"You can't go that way."
	.ENDI
