	; Strings to accompany .\enterable test.zap

	.GSTR STR?5," are"
	.GSTR STR?25," doesn't"
	.GSTR STR?24," don't"
	.GSTR STR?6," is"
	.GSTR STR?1," Try rephrasing the command."
	.GSTR STR?34,"ATTACKBIT"
	.GSTR STR?62,"Baseball."
	.GSTR STR?27,"climb"
	.GSTR STR?12,"close"
	.GSTR STR?63,"Cold showers."
	.GSTR STR?35,"CONTBIT"
	.GSTR STR?36,"DEVICEBIT"
	.GSTR STR?37,"DOORBIT"
	.GSTR STR?38,"EDIBLEBIT"
	.GSTR STR?39,"FEMALEBIT"
	.GSTR STR?3,"get inside"
	.GSTR STR?23,"give things to"
	.GSTR STR?40,"INVISIBLE"
	.GSTR STR?22,"it"
	.GSTR STR?28,"Jumping in place"
	.GSTR STR?41,"KLUDGEBIT"
	.GSTR STR?42,"LIGHTBIT"
	.GSTR STR?13,"lock"
	.GSTR STR?43,"LOCKEDBIT"
	.GSTR STR?4,"look inside"
	.GSTR STR?44,"NARTICLEBIT"
	.GSTR STR?45,"NDESCBIT"
	.GSTR STR?46,"ONBIT"
	.GSTR STR?11,"open"
	.GSTR STR?47,"OPENABLEBIT"
	.GSTR STR?48,"OPENBIT"
	.GSTR STR?49,"PERSONBIT"
	.GSTR STR?7,"pick up"
	.GSTR STR?50,"PLURALBIT"
	.GSTR STR?19,"Pulling"
	.GSTR STR?18,"Pushing"
	.GSTR STR?9,"put things in"
	.GSTR STR?8,"put things on"
	.GSTR STR?15,"read"
	.GSTR STR?51,"READBIT"
	.GSTR STR?31,"Recklessly incinerating"
	.GSTR STR?30,"Rubbing"
	.GSTR STR?52,"SURFACEBIT"
	.GSTR STR?16,"switch on and off"
	.GSTR STR?53,"TAKEBIT"
	.GSTR STR?17,"Taking your frustration out on"
	.GSTR STR?0,"TESTING ENTERABLE"
	.GSTR STR?20,"that"
	.GSTR STR?21,"them"
	.GSTR STR?32,"This is the outdoor area."
	.GSTR STR?33,"This is the testing room."
	.GSTR STR?54,"TOOLBIT"
	.GSTR STR?55,"TOUCHBIT"
	.GSTR STR?56,"TRANSBIT"
	.GSTR STR?57,"TRYTAKEBIT"
	.GSTR STR?14,"unlock"
	.GSTR STR?58,"VEHBIT"
	.GSTR STR?59,"VOWELBIT"
	.GSTR STR?29,"wake"
	.GSTR STR?26,"Waving your hands"
	.GSTR STR?10,"wear"
	.GSTR STR?60,"WEARBIT"
	.GSTR STR?61,"WORNBIT"
	.GSTR STR?2,"You can't go that way."
	.ENDI
