<VERSION XZIP>
<CONSTANT RELEASEID 1>

<CONSTANT GAME-BANNER
  "TESTING ENTERABLE"
>

<ROUTINE GO ()
  <CRLF>
  <CRLF>
  <V-VERSION>
  <CRLF>
  <SETG HERE ,TEST-ROOM>
  <MOVE ,PLAYER ,HERE>
  <V-LOOK>
  <MAIN-LOOP>
>
<COMPILATION-FLAG DEBUGGING-VERBS T>
<INSERT-FILE "parser">

<SET REDEFINE T>

<OBJECT TEST-ROOM
  (IN ROOMS)
  (DESC "room")
  (LDESC "This is the testing room.")
  (FLAGS LIGHTBIT)
  (NORTH OUTDOORS)>
  
<OBJECT STAGE
  (IN TEST-ROOM)
  (DESC "stage")
  (SYNONYM STAGE)
  (FLAGS CONTBIT SURFACEBIT TRANSBIT OPENBIT LIGHTBIT)
  (ACTION STAGE-R)>

<ROUTINE STAGE-R ()
  <COND
    (<VERB? ENTER>
      <MOVE ,PLAYER ,STAGE>
      <TELL "You enter the stage." CR>)>>

<OBJECT FOO
  (IN TEST-ROOM)
  (DESC "foo")
  (SYNONYM FOO)
  (FLAGS TAKEBIT)>

<OBJECT OUTDOORS
  (IN ROOMS)
  (DESC "outdoors")
  (LDESC "This is the outdoor area.")
  (SOUTH TEST-ROOM)
  (FLAGS LIGHTBIT)>