	; Strings to accompany .\vehicledemogame.zap

	.GSTR STR?4," are"
	.GSTR STR?24," doesn't"
	.GSTR STR?23," don't"
	.GSTR STR?5," is"
	.GSTR STR?1," Try rephrasing the command."
	.GSTR STR?35,"A red tricycle stands here."
	.GSTR STR?34,"A small rowboat rests at the edge of the pond."
	.GSTR STR?36,"Baseball."
	.GSTR STR?26,"climb"
	.GSTR STR?11,"close"
	.GSTR STR?37,"Cold showers."
	.GSTR STR?22,"give things to"
	.GSTR STR?21,"it"
	.GSTR STR?27,"Jumping in place"
	.GSTR STR?12,"lock"
	.GSTR STR?3,"look inside"
	.GSTR STR?10,"open"
	.GSTR STR?6,"pick up"
	.GSTR STR?18,"Pulling"
	.GSTR STR?17,"Pushing"
	.GSTR STR?8,"put things in"
	.GSTR STR?7,"put things on"
	.GSTR STR?14,"read"
	.GSTR STR?30,"Recklessly incinerating"
	.GSTR STR?29,"Rubbing"
	.GSTR STR?15,"switch on and off"
	.GSTR STR?16,"Taking your frustration out on"
	.GSTR STR?19,"that"
	.GSTR STR?32,"The rowboat is bobbing near the edge."
	.GSTR STR?20,"them"
	.GSTR STR?13,"unlock"
	.GSTR STR?0,"Vehicle Demo Game
Rideable Vehicles in ZILF
Release 1"
	.GSTR STR?28,"wake"
	.GSTR STR?25,"Waving your hands"
	.GSTR STR?9,"wear"
	.GSTR STR?31,"You are beside a small pond."
	.GSTR STR?33,"You are in a grassy field. A red tricycle and a rowboat are here."
	.GSTR STR?2,"You can't go that way."
	.ENDI
